# Generated by Django 2.1.2 on 2019-03-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('time_sent', models.DateField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='game_started',
            new_name='in_game',
        ),
        migrations.AddField(
            model_name='players',
            name='birthday',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='players',
            name='user_log_ip',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='players',
            name='pseudoname',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='receipt_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sender_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='invite',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_server_gen.Lobby'),
        ),
    ]
