# Generated by Django 2.1.2 on 2019-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0002_auto_20190312_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
