# Generated by Django 2.1.2 on 2019-03-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0003_auto_20190316_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='kicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='time_kicked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tag_server_gen.Players'),
        ),
    ]
