# Generated by Django 2.1.2 on 2019-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0004_auto_20190316_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.IntegerField(default=1001),
        ),
    ]
