# Generated by Django 2.1.2 on 2019-03-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0005_auto_20190319_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='lobby',
        ),
        migrations.AddField(
            model_name='invite',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tag_server_gen.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='time_opened',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
