# Generated by Django 2.1.2 on 2019-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0006_auto_20190321_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='game',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='player',
        ),
        migrations.AddField(
            model_name='lobby',
            name='team',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
