# Generated by Django 2.1.2 on 2019-03-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0007_auto_20190327_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='password',
            field=models.BinaryField(max_length=200),
        ),
    ]
