# Generated by Django 2.1.2 on 2019-04-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0008_auto_20190327_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocatePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_server_gen.Game')),
            ],
        ),
    ]
