# Generated by Django 2.1.2 on 2019-04-21 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0009_locateplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='receipt_id',
            new_name='receiver_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
