# Generated by Django 2.1.2 on 2019-04-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_server_gen', '0010_auto_20190421_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_server_gen.Players'),
        ),
    ]
